language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

env:
    # try all python versions with the latest stable Numpy
    - NUMPY_VERSION=1.7.1 ASTROPY_VERSION=0.3.1 SETUP_CMD='test'

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip -q install --upgrade "numpy==$NUMPY_VERSION"
   - pip -q install --upgrade "astropy==$ASTROPY_VERSION"
   - if [[ $SETUP_CMD == cov ]]; then pip install pytest -q --use-mirrors; fi

script:
   - if [[ $SETUP_CMD == test ]]; then cd spectral_cube/tests/data ; make ; cd ../../../ ; fi
   - if [[ $SETUP_CMD == test ]]; then py.test spectral_cube ; fi