language: c

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - dvipng
            - libgfortran3  # for casatools

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - SETUP_XVFB=True
        - ON_TRAVIS=True
        - INSTALL_CASA=False
        - TOXENV=''
        - TOXARGS='-v'
        - TOXPOSARGS=''

        matrix:
    include:

        # Test with minimal dependencies
        - python: 3.7
          env: TOXENV='py37-test'

        # Test with all dependencies, including CASA, on Python 3.6
        - python: 3.6
          env: TOXENV='py37-test-casa'

        # Test with all dependencies and development versions for key dependencies
        - python: 3.8
          env: TOXENV='py37-test-all-dev'

        # Check for sphinx doc build warnings
        - python: 3.7
          env: TOXENV='build_docs'

script:
    - tox $TOXARGS -- $TOXPOSARGS

after_success:
    - codecov
