language: python

python:
    - 2.7
    - 3.4
    - 3.5
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - SETUP_CMD='test'
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='matplotlib yt'
        - PIP_DEPENDENCIES='aplpy pvextractor'
    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'
        - SETUP_CMD='test' ASTROPY_VERSION='development'
        - SETUP_CMD='test' CONDA_DEPENDENCIES='' PIP_DEPENDENCIES=''

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7

        # Test with bottleneck
        - python: 2.7
          env: CONDA_DEPENDENCIES='matplotlib yt bottleneck'
        - python: 3.5
          env: CONDA_DEPENDENCIES='matplotlib yt bottleneck'

before_install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:

    # radio beam
    - if [[ $SETUP_CMD != egg_info ]]; then $PIP_INSTALL https://github.com/radio-astro-tools/radio_beam/archive/master.zip; fi

script:
   - cd spectral_cube/tests/data ; make ; cd ../../../
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='spectral_cube/tests/coveragerc'; fi
